### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#100]

**Comment by holloway** [comment]
Official migration guidance https://getbootstrap.com/docs/5.0/migration/

**Comment by kesara** [comment]
Pull request: https://github.com/ietf-tools/wagtail_website/pull/125

**Comment by kesara** [comment]
In Bootstrap 5, links are underlined by default (not just on hover), unless they’re part of specific components.
This not covered by #125.
Background: https://github.com/twbs/bootstrap/issues/15304
Is this something we want to keep as it is? @ghwood / @JayDaley

**Comment by kesara** [comment]
Available in production.
