### ISSUE TITLE
The view for BlogPage is database inefficient

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/wagtail_website#11]
The view needs to make better use of prefetch and similar tools to cut down on the number of queries generated by each page view

**Comment by rjsparks** [comment]
Older variants of this application fetched (and displayed) data about _all_ blog entries on any blog entry view, and the page was not performing well.

This may be OBE by the recent rework of the blog page, but it would be good to have someone look at the queries actually executed by the blog view and look for optimization opportunities.

**Comment by kesara** [comment]
Available in production.
