### ISSUE TITLE
Obtain a recent database dump

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/wagtail_website#120]
`install.md` says:
> (Optional) Obtain a recent database dump with name like ietfa.torchbox.*.gz and place in docker/database/ directory. Otherwise, it will start with a fresh database.

*How* does one "obtain a recent database dump"?

**Comment by larseggert** [comment]
Also
> Obtain and unarchive media files into media/ folder.

How?

**Comment by rjsparks** [comment]
Right now, by contacting us. However, we are not yet sharing a developer database directly - that's planned, but we still need to implement password scrubbing. We are providing the bits described here on an as-needed basis to contractors.

**Comment by larseggert** [comment]
OK. I was asking, because I'm not sure whether #119 is caused by me not having these assets locally.

**Comment by larseggert** [comment]
Would it not be possible to build docker images using CI that included the database and media assets, and have `docker-compose` pull them, rather than building locally? Or are there sensitive things in the dumps?

**Comment by rjsparks** [comment]
At the moment there are sensitive things (passwords) in the dumps. See the above comment.
