### ISSUE TITLE
generate a sitemap

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#135]
It would be useful to have a sitemap for the Wagtail website (on its own and available perhaps on the 404 page) 

The process for doing this in Wagtail seems fairly straightforward:

https://docs.wagtail.io/en/stable/reference/contrib/sitemaps.html

It could be placed at:

https://www.ietf.org/about/sitemap.xml

**Comment by kesara** [comment]
[sitemap.xml](https://wwwdev.ietf.org/sitemap.xml) is available on the preview website now.

**Comment by ghwood** [comment]
This looks good to deploy on production.

**Comment by kesara** [comment]
The sitemap is available at root level on production: https://www.ietf.org/sitemap.xml
