### ISSUE TITLE
Remove “gray box” below “Blog” menu item when there are no secondary-menu items

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#14]
When all submenu items are removed from the News & blog top-level menu item (via the Settings->Secondary menu controls in Wagtail admin), there remains a gray box appearing on roll over. See screen shots.

When there are no secondary menu items, there should be no gray box.

With the new approach to IESG statements, I believe it would be OK to remove the "News and Blog" menu options under the Secondary menu controls.

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/5347540/64542995-777b5200-d2f2-11e9-9afc-f0cbb8407056.png">

<img width="286" alt="PastedGraphic-4" src="https://user-images.githubusercontent.com/5347540/64542083-ea83c900-d2f0-11e9-991d-c16fbe40b720.png">

**Comment by rjsparks** [comment]
The real fix was in ede3756
