### ISSUE TITLE
fix email list signup snippets

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#159]
email list signup snippets (https://www.ietf.org/admin/snippets/snippets/mailinglistsignup/) do not work.

For example at:

https://www.ietf.org/how/runningcode/hackathons/111-hackathon/

The snippet should provide a link that initiates a smooth flow to subscribing to the designated list (e.g. to: https://www.ietf.org/mailman/listinfo/hackathon to sign up for hackathon@ietf.org in the current set up)

**Comment by kesara** [comment]
This seems like a configuration issue on the production server because https://wwwdev.ietf.org/how/runningcode/hackathons/111-hackathon/ seems to be working as expected.

**Comment by ghwood** [comment]
Could be related to #30 ?

**Comment by kesara** [comment]
Production server doesn't serve `/misc/disclaimer/` path.
Example:
 development: https://wwwdev.ietf.org/misc/disclaimer/15/
 production: https://www.ietf.org/misc/disclaimer/15/

**Comment by kesara** [comment]
This issue has been fixed on production.
