### ISSUE TITLE
Add github workflow to wagtail website.

### ISSUE THREAD

**Issue by NGPixel** [ietf-tools/wagtail_website#164]
This can be started with automating the creation of docker images and publishing them to https://github.com/features/packages

The wagtail website uses CircleCI to deploy https://wwwdev.ietf.org/ to AWS, this has to remain in CircleCI for time being.

**Comment by kesara** [comment]
Docker images are visible here: https://github.com/ietf-tools/wagtail_website/pkgs/container/wagtail_website

Example command to pull an image:
```
$ docker pull ghcr.io/ietf-tools/wagtail_website:v1.4.4
```

Workflow gets triggered when someone publishes a new release for the wagtail_website
