### ISSUE TITLE
improve handling of photo captions

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#175]
Caption text for image blocks are currently very similar to standard page text, not well connected visually to images when displayed on a page, and thave no option for _not_ displaying the caption.

Ideally, caption text for an image would be:
- visually different from body text
- more closely associated with an image
- optionally not displayed

Screenshot example attached.
<img width="1436" alt="163826375-7db07594-7a42-40b1-9d51-f2e8daf4f17e" src="https://user-images.githubusercontent.com/5347540/163868255-61d3c600-ea98-4349-9b43-d33dee711431.png">

**Comment by kesara** [comment]
Fix has been deployed to wwwdev with #197

**Comment by kesara** [comment]
Comment from JIRA (by @ghwood):
>This is a definite improvement but the caption text below the image appears spaced at least as far away as the non-caption text above. (see [IETF 113 hackathon blog post page](https://wwwdev.ietf.org/blog/ietf113-hackathon/) screenshot from wwwdev on this comment.) Can the vertical spacing between the image and the caption even more closely match the cow image example from the Washington Post?

Hackathon screenshot:
<img width="797" alt="image-20220817-130827" src="https://user-images.githubusercontent.com/1027692/194972081-9f463f8e-0c02-4fd3-a538-86bc16eb1f53.png">

Washington Post screenshot:
<img width="1145" alt="175972085-9c566756-8eee-4abb-8054-ffc1b7165786" src="https://user-images.githubusercontent.com/1027692/194972183-c6ce55a4-3718-4f81-b840-6d6b888184a7.png">
