### ISSUE TITLE
Blog page shows Roles inconsistently

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/wagtail_website#18]
At the time of report, <https://www.ietf.org/blog/mud/?secondary_topic=8&> shows "chair" roles for Eliot and Brian in the right side-bar, but not on the blog article itself.
If there _is_ no role, the separator between it and name should be suppressed.

**Comment by jennifer-richards** [comment]
I am able to reproduce this on my dev system. There appear to be two problems:

  1. The CSS creates the name / role separator whether or not there is a role
  2. The side-bar falls back to an author-associated role when there is no role override, but the main blog article pane does not

**Comment by rjsparks** [comment]
Agreed. 

For 2, don't fall back to the author-associated role. The production database to date has not used them (the datatracker imports have been problematic). If there is no role-override, do not display a role.

(I've been working towards removing the datatracker integration, and so far in that work, I'm replacing the FK from BlogPageAuthor to datatracker.person to a new snippet.person that has no Role.)

**Comment by jennifer-richards** [comment]
Ok. Instead of adding the fall-back behavior to the main display, I will remove it from the side-bar.
