### ISSUE TITLE
Update 404 page to reference RFC 9110/STD 97

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/wagtail_website#193]
From Michael Richardson:

> Don't forget to update the ietf.org 404 page to change
> RFC7230 published in 2014 defines the 404 error code
> to
> STD97, RFC9110.

https://www.ietf.org/404 currently points to the now-obsolete RFCs 7230 and 7231.

(At the same time, it would probably be good to have the email references to ietf-action@ietf.org changed to support@ietf.org.)

Thanks!

**Comment by kesara** [comment]
Updated 404 file is on wwwdev: https://wwwdev.ietf.org/404/
