### ISSUE TITLE
Wagtail error/exception handling needs improvement

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#2]
NOTE: This ticket and the text below was originally copied from the Torchbox ticketing system:

https://projects.torchbox.com/projects/ietf/tickets/211

which requires a password and may no longer be active.

-Greg

++

Hi Tom -

Yup. Check the logs. I should have done that first. Sorry. But it turns out I still would have had to contact you. There was indeed a configuration issue, on our side.... but...

The proximate cause was that Wagtail was sending from "donotreply@ietf.org", but use of that address was restricted to Mailman only. So the SMTP library got a rejection message from Postfix (mail transport.)

The portion of the log that illustrates this is:

File "/usr/lib64/python2.7/smtplib.py", line 747, in sendmail raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {u'glen@amsl.com': (553, '5.7.1 <donotreply@ietf.org>: Sender address rejected: not logged in')}
I've opened permission for that address, and the process works now.... for now....

But I suggest there still ought to be better exception handling for this than a crash. If there is a problem with sending the email, a more polite failure message, and a referral of the user to https://www.ietf.org/contact/ with a request to contact us, would probably be a more desirable option.

I don't know the current status of anything, but any time there is an interaction with server processes, there ought to be some kind of try/catch handling. I think? I leave it up to you to determine what's best here.

Thanks so much!
Glen

+++

Hi Glen,

We think the best approach is to design and implement an enhanced 500 error page for internal server errors. We've spent around an hour looking into this for you this month.

If you are happy with this approach, we'll spend further time providing a design and development estimate for the work and let you know how long we expect this error message to take.

To speed up the estimate, it would help if you could provide some messaging for the error message - or if you prefer we could recommend some copy for you. 

Many thanks,
Beth

**Comment by rjsparks** [comment]
The right thing to do with this is wrap the points the website sends mail with a try/catch and show something to the user about the email failing to send (probably by using Django's Message framework).

**Comment by JayDaley** [comment]
Requirement: Catch 500 errors (or other major errors) and put up a "Oops something went wrong" page.

**Comment by kesara** [comment]
Available in production.
