### ISSUE TITLE
Consider revising Area templates

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#22]
The original idea behind Area pages was to provide a general overview of IETF areas with links to related items (working groups, recent RFCs, Active drafts) in the Datatracker. This fit with the general goal of connecting the public-facing www.ietf.org with the "work" in the IETF, as represented by objects in Datatracker.  However, the implementation details of the page template (e.g. using alphabetical sorting to list RFCs and WGs) meant that the auto-generated content of the pages are not useful.

A mock up, just to provide an idea of what the templated does, is staged here:
https://wwwtest.ietf.org/topics/areas/security/

Ideally, there would be a way of keeping the general idea behind the pages, but reconsidering the implementation details so that the pages would be more useful or representative.

For example, is there a way to list all the WGs in an area? (maybe omit the description, but include the name, abbreviation, and links to the main page and charter page in Datatracker. 

Is it possible to leverage the "Newly adopted I-Ds in WGs" information to highlight new work in WGs related to an area?

For RFCs, is there a way to list the most recently published Standards-track RFCs that were the product of an Area WG?

If there isn't a way to adapt the template so it can be useful, it might be worth removing it to avoid possible unintentional use.

**Comment by rjsparks** [comment]
What was ephemerally available at wwwtest.ietf.org:
Screenshot_2019-09-17 Security

**Comment by ghwood** [comment]
Use of Area Page templates has been deprecated, so this issue is no longer relevant.
