### ISSUE TITLE
Consider revising Topic templates

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#23]
The Topic templates were intended to work with Area pages to describe and relate general topics being discussed in "the general market" (e.g. IoT) to the work of the IETF. However, the non-use of Area templates has meant that the layout logic of the Topic template no longer applies. For example, the peer-page menu provided on the side is too far down to be useful, and the space in the main part of the page body intended for Area pages, now is blank.

Here is an example of the Topic page template in action
https://www.ietf.org/topics/netmgmt/

Here is an example of the Topic page template how it (roughly) was intended to be used:
https://wwwtest.ietf.org/topics/netmgmt/

There would still be value in connecting general topics of interest in the Internet (IoT, new transport technologies, Privacy & security) with the work of the IETF, but it may be better to consider how that might be done differently. For example, could Blog posts (or other pages) be tagged to relate to one or more Topics of interest with the latest 3-5 (Page title and Search description) being listed in the body?

**Comment by rjsparks** [comment]
What was ephemerally at the wwwtest link above:
![Screen Shot 2019-09-17 at 5 00 45 PM](https://user-images.githubusercontent.com/10996692/65082967-e39e2b80-d96c-11e9-8e92-0bdaef370e6a.png)

**Comment by ghwood** [comment]
This issue has been addressed by the re-implemented page templates.
