### ISSUE TITLE
Styling around the next/previous entry controls on blog pages is broken

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/wagtail_website#24]
The container for the next and previous entry boxes at the bottom of the page extends all the way across the screen and is above the containers for the blog entries in the right scrollbar.

So, if you mouse to the right of the "Next" box, the cursor sees no link (try moving the mouse on a blog entry just above and just below the top of the Next box).

If the blog entry is small enough to fit entirely under that container, you can't click on it. If it happens to be the last entry, there's no way to move it to where you can click on it.

**Comment by ghwood** [comment]
This is fixed with the reimplemented page templates.
