### ISSUE TITLE
padding-top on .pt-lg-5 leaves too much whitespace

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#241]
.pt-lg-5 has a 3rem padding-top.  When the first item in the body text is text then that's the total whitespace there, but when it is an h2 heading, which is common, that has a 2rem margin-top and so there is a 5rem whitespace, which is far too large.  Better to reduce the padding-top of .pt-lg-5 to 1rem so that the maximum whitespace is only ever 3rem.

**Comment by katie-day** [comment]
Hi @JayDaley, could you please provide links to pages where we could see examples of this issue.

**Comment by katie-day** [comment]
Example of an `h2` combined with `.pt-lg-5` making the space too large: https://www.ietf.org/how/lists/ 
![Screen Shot 2022-11-02 at 11 31 18 AM](https://user-images.githubusercontent.com/13722738/199354243-af29dc53-c72c-4895-a411-bd01c299593e.png)

Example of when paragraph text is first in the body:
https://www.ietf.org/how/ids/

![Screen Shot 2022-11-02 at 11 36 06 AM](https://user-images.githubusercontent.com/13722738/199354921-6565962d-4865-4c12-b2c3-dada053b39b5.png)
