### ISSUE TITLE
Use latest Wagtail 4.1.*

### ISSUE THREAD

**Issue by kesara** [ietf-tools/wagtail_website#242]
At the moment latest wagtail release is [4.0.2](https://docs.wagtail.org/en/stable/releases/4.0.2.html#wagtail-4-0-2-release-notes).

wagtail_website needs to be updated to latest wagtail release.
This will require backend code changes. See [4.0 Upgrade Considerations](https://docs.wagtail.org/en/stable/releases/4.0.html#upgrade-considerations).

**Comment by gdelavil** [comment]
We'd now want to upgrade to version 4.1.1, which releases some fixes for the new LTS, version 4.1.
