### ISSUE TITLE
Add new snippet to include "Note Well"

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/wagtail_website#30]
> (EDIT: See https://github.com/ietf-tools/wagtail_website/issues/30#issuecomment-1493486292 for the requirements)

The snippet viewer for MailingListSignup objects uses a custom view and template to show a page with Note Well text with the link to the signup page (or email address) for the mailing list in question.

At the moment, the template contains an older version of the Note Well text.

We have a Note Well page at /about/note-well. Perhaps this custom view could leverage the bits used to serve that page so there was only one local copy to maintain?

**Comment by russhousley** [comment]
One place for the Secretariat to update when the Note Well test changes would be the ideal.

**Comment by ghwood** [comment]
To restate: 

+ The page should use the same text as the official note-well page, whatever that is at the moment the page 

+ The link (signup page or email address) should be displayed in a way that is more clearly a button.

**Comment by rjsparks** [comment]
Again - the secretariat should ideally only have to edit one thing. Not edit one thing and copy it to a bunch of other places. This app should go _get_ the bits of the canonical thing, not store a copy of them.

**Comment by kesara** [comment]
The expected outcome is a brand new snippet showing the "Note Well" text.
The new snippet should be able to insert into different content pages.
As described in #194, "Note Well" has to be fetched from a GitHub repository.
