### ISSUE TITLE
Pagination of filtered glossary items which render in one page makes no sense

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/wagtail_website#31]
At <https://www.ietf.org/about/glossary/?query=Blue%20sheets>, there are stanzas that look like:

`

                                &laquo;
                            

                            1

                            
                                &raquo;
`
These are artifacts of paginating glossary search results. When there is more than one page of results, these blocks have links to the other pages. When there's only one page, however, the block is meaningless ans should be suppressed.

**Comment by ghwood** [comment]
As I'm not able to reproduce this issue on the current site I believe it has been addressed and am closing it.
