### ISSUE TITLE
Update to Wagtail 5.1

### ISSUE THREAD

**Issue by kesara** [ietf-tools/wagtail_website#322]
The wagtail_website is on Wagtail 4.1.1 at the moment.
The latest Wagtail release is 5.1

Release notes: https://docs.wagtail.org/en/stable/releases/5.1.html

**Comment by mgax** [comment]
I think this can be marked as "done"; https://github.com/ietf-tools/wagtail_website/pull/350 upgraded Wagtail to version 5.2.1.
