### ISSUE TITLE
links to RFCs broken

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#36]
It looks like links on several pages to RFCs that were previously linked no longer work.

For example the link to RFC 2026 at the top of:

https://www.ietf.org/standards/process/informal/

Does not work, though it still appears to be a link. Here's a snapshot of that page where the link works:

https://web.archive.org/web/20190912203705/https://www.ietf.org/standards/process/informal/

It is also the case that in the Wagtail editing interface, the text looks like a link, but it is not possible to edit the link by choosing the "link" icon (see screenshot attached). The link *can* be undone by clicking the "unlink" icon.

This appears in a variety of links on this page, and also on other pages ( ) but not for every link. For example at the top of https://www.ietf.org/standards/process/ of the four parts of text that look like a link, 2 links work and 2 do not.

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/5347540/76032730-83924600-5f08-11ea-983c-44a99078fe3b.png">

**Comment by rjsparks** [comment]
This is a consequence of a small, but important, change made in the long string of migrations not making it into the merge to trunk. The snippets.RFCs and Charters should have had pks matching the older datatracker tables of the same names. This was to avoid rewriting the source for each page where the LinkChoosers and RichTextLinkHandlers have put primary keys into attributes of links on those source pages. I think the quickest resolution will be to use a rawsql migration to empty those snippet tables and repopulate them with the pks where the migrations should have put them in the first place.
