### ISSUE TITLE
Ordering of "next" and "previous" blog pages reversed

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/wagtail_website#38]
At the bottom of a blog page, the "next" button links to the blog page that was published just before the current page. The "previous" button links to the blog page published just after the current page. Wrapping around to the start/end of the list is consistent with this ordering.

This seems backwards to me - I'd expect "previous" to be the page published before the current one.

Apologies if this is intentional and I've misunderstood the intent.

**Comment by rjsparks** [comment]
I agree that it's backwards.

**Comment by rjsparks** [comment]
Greg - I'm removing page-template from this one. The rest of the places we're using the tag, the problem lies in the way the html is constructed. This one is lies in logic.

**Comment by ghwood** [comment]
Agree with all this. 

Moreover, I notice that "Previous" (which should be "Next") currently on the *latest* blog post points to the *oldest* post. 

Instead, on the post with the most recent publication date, the "Previous" box should highlight/link to the next most recent post and the "Next" box should be empty (including not showing "Next"). Attached screenshot illustrates this. 
![image](https://user-images.githubusercontent.com/5347540/123862874-e1fde780-d8f6-11eb-8c94-d27554f3bbbe.png)

**Comment by rjsparks** [comment]
@ghwood - Instead of an empty box as you draw above - how about a box that says in subtle text "This is the most recent blog entry"?

At the other end, the previous box could say "This is the first blog entry".

**Comment by ghwood** [comment]
I personally don't think it would be necessary but if it would make things clearer I suggest this (subtle) text:

"You are viewing the most recent blog post."

and

"You are viewing the first blog post."

**Comment by kesara** [comment]
Available in production.
