### ISSUE TITLE
Rename the project name to website

### ISSUE THREAD

**Issue by kesara** [ietf-tools/wagtail_website#386]
Rename the project name to `website`.

**Comment by NGPixel** [comment]
![DO IT](https://github.com/ietf-tools/wagtail_website/assets/15522395/989e253b-46e6-47bf-9b78-ed2f5a14d8c8)

**Comment by rjsparks** [comment]
maybe something a little less generic? Maybe www?
Think of how people that are hunting for where to file issues will file issues.

**Comment by NGPixel** [comment]
`www` is my preferred choice as well, as it corresponds to the hostname.

**Comment by kesara** [comment]
`www` might confuse some people who are already confused about `datatracker`.
I am not against using `www`.

**Comment by kesara** [comment]
Fixed by #387
