### ISSUE TITLE
Several pages are not currently editable

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/wagtail_website#46]
We are running into the drafttail issue discussed in this thread:
https://github.com/wagtail/wagtail/issues/4602

Around 68 StandardPages are affected.

**Comment by ghwood** [comment]
The embedded link in the comment doesn't work for me. I think it is intended to point here: https://github.com/wagtail/wagtail/issues/4602

**Comment by rjsparks** [comment]
I fixed the original link. Github must have changed its comment parser or renderer since I first added it, all I had to do with the edit was resupply the same URL.

**Comment by ghwood** [comment]
@rjsparks is this still an issue for us? I haven't run into it and haven't heard about it for a while.

**Comment by rjsparks** [comment]
I've re-confirmed we no longer have the issue for which this ticket was opened.
