### ISSUE TITLE
CSRF cookie error for cached Form pages

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#49]
On this page:

https://www.ietf.org/topics/keywords/

When a form page (https://www.ietf.org/topics/keywords/keyword-suggestions/) is accessed via the call to action snippet, submitting the form returns a CSRF error. (screenshot attached) for a submission that seems valid.

When the same form page is accessed via a link embedded in the "Suggestions for additional keywords” text on the page, the form operates correctly.

The form page should work the same when accessed from any link on the www.ietf.org site.
![image-1](https://user-images.githubusercontent.com/5347540/86254535-f0021680-bb83-11ea-8ef1-17ab6dbda27f.png)
![image-3](https://user-images.githubusercontent.com/5347540/86254537-f09aad00-bb83-11ea-934a-7215abc6b370.png)
![image-2](https://user-images.githubusercontent.com/5347540/86254538-f09aad00-bb83-11ea-886a-7aebdd53cb6d.png)

**Comment by rjsparks** [comment]
This is almost certainly just a caching issue. Right now, the forms under that page are not protected from CDN caching, so you are getting the empty form with someone else's CSRF token in it.

**Comment by ghwood** [comment]
After further testing, I think it is a caching issue as I can now replicate the error with both methods of accessing the form so am closing this issue.

**Comment by ghwood** [comment]
After investigation and clear thinking from @rjsparks I've reopened this issue (and edited the title) so that what seems to be the underlying cause of the CSRF cookie error remains in view: caching for webpages prompts the error.

CDN caching seems not to be enabled for www.ietf.org/forms so that any form pages published there seem to work fine.

There are a few Wagtail-maintained form pages that are *not* in ../forms directory. (screenshot attached). There may other form pages not tracked by Wagtail.

An approach for dealing with these should be developed. E.g. for the form pages within Wagtail, they might just be moved to ../forms

<img width="1023" alt="Screen Shot 2020-07-01 at 12 18 29 PM" src="https://user-images.githubusercontent.com/5347540/86267893-622f2700-bb95-11ea-8687-9934884925a6.png">

**Comment by ghwood** [comment]
This is no longer an issue as all form pages are now in the /forms directory and future forms are to be created there.
