### ISSUE TITLE
Mailing list signup Snippet does not work as expected.

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#8]
A bug was reported on www.ietf.org via the RT queue (webmaster@ietf.org) and I’m not sure how to handle it. 

Here’s the pointer to the original ticket (the text of which is below):

https://www.ietf.org/rt/Ticket/Display.html?id=278525

Here are's what I've found after poking at wwwtest.ietf.org. The issue seems to be generalized with the “Mailing list signups” snippets.

Instead of linking to the URL specified in a snippet, the link is to something like:

https://wwwtest.ietf.org/misc/disclaimer/5/ 

(The last number will change depending on the Snippet.)

On wwwtest.ietf.org, I’ve tried creating a brand new Mailing list signup snippet using both the “pick a mailing list” and  and it too has the problem. The example I created is at the bottom (currently) of these pages:

https://wwwtest.ietf.org/how/runningcode/hackathons/107-hackathon/
(Using QUIC in the WG mailing list sign up selection feature)

https://wwwtest.ietf.org/how/runningcode/hackathons/106-hackathon/
(Using the Sign Up field to specify a URL)

Screenshots attached.
<img width="1280" alt="PastedGraphic-8" src="https://user-images.githubusercontent.com/5347540/63442055-6bd9f100-c400-11e9-8b60-07e9a9c2714e.png">
<img width="1280" alt="PastedGraphic-9" src="https://user-images.githubusercontent.com/5347540/63442056-6bd9f100-c400-11e9-853b-beea8cd672a2.png">

**Comment by ghwood** [comment]
An update: Looking at www.ietf.org and wwwstaging.ietf.org today, it looks like the admin interface for email snippets has been effectively disabled (snippets aren't shown). However, it does seem to still be possible to add snippets to webpages and they seem to work. Screenshots attached.
<img width="1343" alt="Screen Shot 2019-09-05 at 9 21 28 AM" src="https://user-images.githubusercontent.com/5347540/64345858-11738f80-cfbf-11e9-9d00-1491dd165d37.png">
<img width="1343" alt="Screen Shot 2019-09-05 at 9 18 21 AM" src="https://user-images.githubusercontent.com/5347540/64345859-11738f80-cfbf-11e9-959f-6df9ce2a1f4f.png">

**Comment by ghwood** [comment]
For the page at https://www.ietf.org/how/lists/discussion/ I have worked around the Mailing List snippet failure by substituting a Call to Action snippet, which still seems to work. Perhaps there could be a reworking of the Mailing List snippet feature to mirror how "Calls to Action" work? We'd need to consider details but the ability to have 2 different Calls on the same page (which is what effectively the mailing list snippets allowed) is useful.

**Comment by rjsparks** [comment]
This was an apache proxy configuration issue (/misc was not proxied correctly).
