### ISSUE TITLE
reduce table padding

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#85]
current padding is:

   .block-table__container td, .block-table__container th, .block-table td, .block-table th {
       padding: 20px;
   }

it might be reduced to something like:

   .block-table__container td, .block-table__container th, .block-table td, .block-table th {
       padding: 10px;
   }

**Comment by JayDaley** [comment]
Duplicate of #76

**Comment by JayDaley** [comment]
closed as duplicate
