### ISSUE TITLE
twitter sharing button does not work as expected on blog post page template

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#88]
When the twitter icon under "Share this page" is clicked, the visitor is taken to twitter and a dialogue to tweet is presented, but the dialog does not include any content, even when the "Social text" and "Social image" fields on the page's Promote tab are populated. (screen shot attached). An example is:

https://www.ietf.org/blog/anrw21-deadline-extended/

Instead, when the twitter icon is clicked, the visitor should be taken to twitter and presented with a dialogue to tweet pre-filled with the content in the "Social text" and Social Image fields.
<img width="669" alt="Screen Shot 2021-05-11 at 3 36 29 PM" src="https://user-images.githubusercontent.com/5347540/117874761-688b3680-b26f-11eb-8b76-0b4e98ddb8e5.png">

**Comment by kesara** [comment]
Available in production.
