### ISSUE TITLE
Event page introduction tool tip does not reflect actual introduction field limit

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#90]
The tool tip indicates a limit of 511 characters but the actual limit is 200. 

The tool tip should match the actual limit.

It would also be more consistent if the limit matched other page templates, which have 255 character limits for introduction fields.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/5347540/122252350-42be0680-ce99-11eb-8118-c2336b3226d4.png">

**Comment by JayDaley** [comment]
I would prefer if this could be the 511 as per the tool tip because the Event page puts the introduction text on top of a background image and therefore provides a good contrast background for longer text in comparison to other page types.
