### ISSUE TITLE
Turn on additional features in the Editor

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#92]
As per the [documentation](https://docs.wagtail.io/en/stable/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field), Wagtail supports additional features in the Editor that are not turned on by default:
* **code** - inline code
* **superscript**, **subscript**, **strikethrough** - text formatting
* **blockquote** - blockquote

Please enable these

**Comment by JayDaley** [comment]
Looks like this is a sysadmin thing not related to this codebase.

**Comment by JayDaley** [comment]
Mistakenly closed.

**Comment by kesara** [comment]
Available in production.
