### ISSUE TITLE
Headings H1, H2, H3, H4 are not distinct enough from each other and too large

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#94]
If you use multiple heading levels on a single page, then it is hard to tell what level is which.  They also take up far too much space.  This has led to multiple poor workarounds being used, such as using H3 instead of H2 when that's the only heading used, and using H2 and H4 when two levels are required.

They need redesigning to be smaller and more distinct from each other, so that the heading levels are clear on a page that uses a number of them.

**Comment by kesara** [comment]
Available in production.
