### ISSUE TITLE
Add support for HTML tables in page editor

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#95]
Instructions here https://docs.wagtail.io/en/stable/reference/contrib/table_block.html

**Comment by kesara** [comment]
Table block is already present in the current wagtail site.
And it can be added selecting **table button** on content fields.
For example on **Standard Page**:
<img width="1231" alt="Screen Shot 2021-07-05 at 12 07 13 PM" src="https://user-images.githubusercontent.com/1027692/124403300-c331a200-dd89-11eb-8694-837f6df7d129.png">

Is there a certain page type that this is missing?

**Comment by JayDaley** [comment]
Sorry, I misread this.   I was trying to get HTML links into tables and it turns out that the tableblock module doesn't support it.  I'll close this and look at it further.

**Comment by kesara** [comment]
May be this feature what you after: https://github.com/wagtail/wagtail/issues/6041

**Comment by kesara** [comment]
FWIW current table block accepts HTML, but you have to write the html tag and it shows the rendered output when you complete the tag.

**Comment by JayDaley** [comment]
Yes for some pages, such as https://www.ietf.org/about/administration/rfps-and-contracts/ we write the tables as pure HTML just so that we can add links in the tables. I was hoping that there was an easier way but it appears not.
