### ISSUE TITLE
Edit 404 page to remove link to RFC

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#99]
Nice, but confusing.  Remove link and edit heading text along the lines of "Did you know that the IETF is where the 404 error code is defined"

**Comment by kesara** [comment]
Released with [v1.2.0](https://github.com/ietf-tools/wagtail_website/releases/tag/v1.2.0).

**Comment by kesara** [comment]
The way 404 pages are configured in production server requires to copy the static HTML of Wagtail 404 page to another location.

**Comment by kesara** [comment]
This has been configured correctly on production server.
